server:
  port: 8080

swagger:
  baseurl: "http://localhost:${server.port}/"
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"

oidc:
  jwk-set-uri: http://localhost:9900/auth/realms/shop/protocol/openid-connect/certs