server:
  port: 8080

keycloak:
  realm:
    baseUri: http://localhost:9900/auth/realms/shop

oidc:
  jwk-set-uri: "${keycloak.realm.baseUri}/protocol/openid-connect/certs"

swagger:
  baseurl: "http://localhost:${server.port}/"
springdoc:
  swagger-ui:
    path: "/swagger-ui"
    tokenUri: "${keycloak.realm.baseUri}/protocol/openid-connect/token"
    authorizationUri: "${keycloak.realm.baseUri}/protocol/openid-connect/auth"
  api-docs:
    path: "/api-docs"